# Generated by Django 6.0.3 on 2026-03-20 03:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarioGuerra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('dia_semana', models.CharField(choices=[('SEG', 'Segunda-feira'), ('TER', 'Terça-feira'), ('QUA', 'Quarta-feira'), ('QUI', 'Quinta-feira'), ('SEX', 'Sexta-feira'), ('SAB', 'Sábado'), ('DOM', 'Domingo')], max_length=3)),
                ('horario', models.TimeField()),
                ('imagem_guerra', models.ImageField(blank=True, null=True, upload_to='guerras_fotos/')),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ordem_hierarquia', models.IntegerField(help_text='Ex: 1 para Alta Cúpula, 2 para Líderes, etc.')),
            ],
            options={
                'ordering': ['ordem_hierarquia'],
            },
        ),
        migrations.CreateModel(
            name='NoticiaJornal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('conteudo', models.TextField()),
                ('imagem_capa', models.ImageField(blank=True, null=True, upload_to='jornal_fotos/')),
                ('data_publicacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('autor', models.CharField(default='Administração', max_length=50)),
            ],
            options={
                'ordering': ['-data_publicacao'],
            },
        ),
        migrations.CreateModel(
            name='MembroStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=50)),
                ('cargo_especifico', models.CharField(blank=True, max_length=100, null=True)),
                ('foto_boneco', models.ImageField(default='default_skin.png', upload_to='staff_fotos/')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoriastaff')),
            ],
        ),
    ]
